# EKE-DX-WIRE release pipeline
# Build -> Test -> Commit -> Push -> Pull Request
# Intended to be launched from the development GUI or directly from PowerShell.

[CmdletBinding()]
param(
    [switch]$BuildOnly
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

function Step([string]$Message) {
    Write-Host ""
    Write-Host ("[DX-RELEASE] " + $Message) -ForegroundColor Cyan
}

function Fail([string]$Message) {
    Write-Host ""
    Write-Host ("[DX-RELEASE] FAILED: " + $Message) -ForegroundColor Red
    Write-Host ""
    exit 1
}

function Invoke-Checked([string]$File, [string[]]$Arguments) {
    & $File @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw ("Command failed with exit code {0}: {1} {2}" -f $LASTEXITCODE, $File, ($Arguments -join " "))
    }
}

try {
    Step "Repository: $repoRoot"

    if (-not (Test-Path (Join-Path $repoRoot ".git"))) {
        Fail "Repository root could not be verified."
    }

    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Fail "git.exe was not found on PATH."
    }

    $branch = (git rev-parse --abbrev-ref HEAD).Trim()
    if ([string]::IsNullOrWhiteSpace($branch) -or $branch -eq "HEAD") {
        Fail "Repository is in detached HEAD state."
    }

    Write-Host "Current branch: $branch"

    Step "Configuring Release build"
    Invoke-Checked "cmake" @("-S", ".", "-B", "build")

    Step "Building Release"
    Invoke-Checked "cmake" @("--build", "build", "--config", "Release", "--parallel")

    Step "Running Release tests"
    Invoke-Checked "ctest" @("--test-dir", "build", "-C", "Release", "--output-on-failure")

    if ($BuildOnly) {
        Write-Host ""
        Write-Host "[DX-RELEASE] BUILD + TEST COMPLETE" -ForegroundColor Green
        exit 0
    }

    Step "Checking GitHub CLI"
    if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
        Fail "GitHub CLI (gh.exe) is required for automatic PR creation."
    }
    gh auth status
    if ($LASTEXITCODE -ne 0) {
        Fail "GitHub CLI is not authenticated. Run: gh auth login"
    }

    Step "Checking working tree"
    $status = @(git status --short)
    if ($status.Count -eq 0) {
        Write-Host "Working tree is clean."
    } else {
        Write-Host "Changes to be committed:"
        $status | ForEach-Object { Write-Host "  $_" }
    }

    if ($branch -eq "main" -or $branch -eq "master") {
        Write-Host ""
        $newBranch = Read-Host "Enter feature branch name"
        if ([string]::IsNullOrWhiteSpace($newBranch)) {
            Fail "A feature branch is required; main/master is never used for automatic PR commits."
        }

        $newBranch = $newBranch.Trim()
        Invoke-Checked "git" @("switch", "-c", $newBranch)
        $branch = (git rev-parse --abbrev-ref HEAD).Trim()
        Write-Host "Created and switched to: $branch" -ForegroundColor Green
    }

    $commitMessage = Read-Host "Commit message (Enter = use current branch name)"
    if ([string]::IsNullOrWhiteSpace($commitMessage)) {
        $commitMessage = $branch
    }

    Step "Creating commit"
    Invoke-Checked "git" @("add", "-A")

    $staged = @(git diff --cached --name-only)
    if ($staged.Count -eq 0) {
        Write-Host "No new staged changes. Continuing with existing branch commits."
    } else {
        Invoke-Checked "git" @("commit", "-m", $commitMessage)
    }

    Step "Pushing branch"
    Invoke-Checked "git" @("push", "-u", "origin", $branch)

    Step "Checking for an existing open PR"
    $existingPr = (gh pr list --head $branch --base main --state open --json url --jq ".[0].url" 2>$null).Trim()
    if (-not [string]::IsNullOrWhiteSpace($existingPr)) {
        Write-Host ""
        Write-Host "[DX-RELEASE] Existing PR: $existingPr" -ForegroundColor Green
        Write-Host ""
        exit 0
    }

    $prTitle = Read-Host "PR title (Enter = use commit message)"
    if ([string]::IsNullOrWhiteSpace($prTitle)) {
        $prTitle = $commitMessage
    }

    $headSha = (git rev-parse HEAD).Trim()
    $body = @"
## Summary

Automated release generated by EKE-DX-WIRE development tooling.

## Validation

- CMake Release configure: PASS
- Release build: PASS
- CTest Release suite: PASS
- HEAD: $headSha

## Workflow

Build -> Test -> Commit -> Push -> Pull Request

This automation does not merge pull requests.
"@

    Step "Creating pull request"
    $prUrl = gh pr create --base main --head $branch --title $prTitle --body $body
    if ($LASTEXITCODE -ne 0) {
        throw "GitHub CLI failed to create the pull request."
    }

    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host " DX-EXTRACTOR RELEASE COMPLETE" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "Branch: $branch"
    Write-Host "Commit: $headSha"
    Write-Host "PR:     $prUrl"
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
}
catch {
    Fail $_.Exception.Message
}
